import { APIRequestContext, Page, Request, request } from '@playwright/test';

const getQuotationsQuery = `
  query GetQuotations($quotationStatuses: [KHQuotationStatus!]) {
    get_quotations(quotation_statuses: $quotationStatuses) {
      id
      name
      shared
      isDefault
      fulfillment_instructions
      reference
      total_number_quotation_lines
      __typename
    }
  }
`;

const defaultQuotationQuery = `
  query DefaultQuotation {
    default_quotation(input: { force_create_new_default_quotation: true }) {
      id
      name
      shared
      isDefault
      fulfillment_instructions
      reference
      total_number_quotation_lines
      __typename
    }
  }
`;

const quotationCountsQuery = `
  query QuotationCounts {
    default_quotation {
      id
      quotation_lines {
        id
      }
    }
  }
`;

const deleteQuotationLineMutation = `
  mutation DeleteQuotationLine($input: KHDeleteQuotationLineInput!) {
    delete_quotation_line(input: $input) {
      id
      __typename
    }
  }
`;

const forwardedHeaderNames = [
  'accept-language',
  'ctx-bot-detected',
  'ctx-corporate-identity',
  'ctx-locale',
  'urlslug',
  'x-channel-version',
  'x-client-instance-id',
  'x-features',
  'x-rid',
];

export interface Quotation {
  id: string;
  name: string | null;
  shared: boolean;
  isDefault: boolean;
  fulfillment_instructions: string | null;
  reference: string | null;
  total_number_quotation_lines: number;
}

export interface QuotationLine {
  id: string;
}

interface GetQuotationsResponse {
  data?: { get_quotations: Quotation[] };
  errors?: Array<{ message: string }>;
}

interface DefaultQuotationResponse {
  data?: { default_quotation: Quotation };
  errors?: Array<{ message: string }>;
}

interface DeleteQuotationLineResponse {
  data?: { delete_quotation_line: { id: string } };
  errors?: Array<{ message: string }>;
}

interface QuotationCountsResponse {
  data?: {
    default_quotation: {
      id: string;
      quotation_lines: QuotationLine[];
    } | null;
  };
  errors?: Array<{ message: string }>;
}

/**
 * Executes quotation GraphQL requests inside the current browser page.
 * Start capturing before navigation so the helper can reuse deployment-specific
 * GraphQL headers generated by the web application.
 */
export class QuotationApi {
  private graphqlHeaders: Record<string, string> = {};
  private client?: APIRequestContext;

  constructor(private readonly page: Page) {}

  start(): void {
    this.page.on('request', this.captureGraphqlHeaders);
  }

  /**
   * Clones the authenticated browser storage into an API client.
   * Call this after the login flow has completed.
   */
  async initialize(): Promise<void> {
    await this.client?.dispose();
    this.client = await request.newContext({
      storageState: await this.page.context().storageState(),
    });
  }

  async dispose(): Promise<void> {
    await this.client?.dispose();
    this.client = undefined;
  }

  async getOpenQuotations(): Promise<Quotation[]> {
    await this.getDefaultQuotation();
    const response = await this.execute('GetQuotations', { quotationStatuses: 'OPEN' }, getQuotationsQuery);

    const body = response.body as GetQuotationsResponse;
    this.throwOnError('GetQuotations', response.status, body.errors);

    return body.data?.get_quotations ?? [];
  }

  private async getDefaultQuotation(): Promise<Quotation> {
    const response = await this.execute('DefaultQuotation', {}, defaultQuotationQuery);
    const body = response.body as DefaultQuotationResponse;
    this.throwOnError('DefaultQuotation', response.status, body.errors);

    const quotation = body.data?.default_quotation;
    if (!quotation) {
      throw new Error('DefaultQuotation succeeded without returning a quotation');
    }

    return quotation;
  }

  async deleteQuotationLine(
    quotationId: string,
    quotationLineId: string,
    quotationState = '',
  ): Promise<string> {
    const response = await this.execute(
      'DeleteQuotationLine',
      {
        input: {
          quotation_id: quotationId,
          quotation_line_id: quotationLineId,
          quotation_state: quotationState,
        },
      },
      deleteQuotationLineMutation,
    );

    const body = response.body as DeleteQuotationLineResponse;
    this.throwOnError('DeleteQuotationLine', response.status, body.errors);

    const deletedLineId = body.data?.delete_quotation_line.id;
    if (!deletedLineId) {
      throw new Error('DeleteQuotationLine succeeded without returning a quotation line id');
    }

    return deletedLineId;
  }

  async clearOpenQuotationLines(): Promise<void> {
    await this.getOpenQuotations();
    const quotation = await this.getDefaultQuotationWithLines();
    if (!quotation) return;

    await Promise.all(
      quotation.quotation_lines.map((line) =>
        this.deleteQuotationLine(quotation.id, line.id),
      ),
    );
  }

  private async getDefaultQuotationWithLines(): Promise<{
    id: string;
    quotation_lines: QuotationLine[];
  } | null> {
    const response = await this.execute('QuotationCounts', {}, quotationCountsQuery);
    const body = response.body as QuotationCountsResponse;
    this.throwOnError('QuotationCounts', response.status, body.errors);

    return body.data?.default_quotation ?? null;
  }

  private async execute(operationName: string, variables: object, query: string) {
    if (!this.client) {
      throw new Error('QuotationApi is not initialized. Call initialize() after login.');
    }

    const response = await this.client.post(
      new URL('/graphql/webshop', this.page.url()).toString(),
      {
        headers: {
          accept: '*/*',
          'content-type': 'application/json',
          referer: this.page.url(),
          ...this.graphqlHeaders,
          'x-rid': crypto.randomUUID(),
        },
        data: { operationName, variables, query },
      },
    );

    return { status: response.status(), body: await response.json() };
  }

  private throwOnError(
    operationName: string,
    status: number,
    errors?: Array<{ message: string }>,
  ): void {
    if (status && !errors) return;

    throw new Error(
      `${operationName} failed with status ${status}: ${errors?.map(({ message }) => message).join(', ') ?? 'unknown error'}`,
    );
  }

  private captureGraphqlHeaders = (request: Request): void => {
    if (!request.url().includes('/graphql/webshop')) return;

    const headers = request.headers();
    this.graphqlHeaders = Object.fromEntries(
      forwardedHeaderNames.flatMap((name) =>
        headers[name] ? [[name, headers[name]]] : [],
      ),
    );
  };
}
